name: locale
description: This is a port of java.util.locale to dart
version: 0.0.1
author: Joris Hermans <hermansj@gmail.com>
homepage: http://github.com/jorishermans/locale
#dependencies:
#  lib_name: any
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
