name: locale
description: This is a port of java.util.locale to dart
version: 0.1.1+2
author: Joris Hermans <hermansj@gmail.com>
homepage: https://github.com/jorishermans/locale.dart
#dependencies:
#  lib_name: any
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
